export const getCurrentUser = async (req, res) => {
    try {
        // Retorna el usuario actual extra√≠do de la solicitud
        res.send(req.user)
    } catch (error) {
        res.status(500).send('Error interno del servidor')
    }
}
